### ISSUE TITLE
Demo app

### ISSUE THREAD

**Issue by jorgepedret** [codeschool-courses/anatomyofbackbone#1]
Hey guys,

It'd be awesome if you had a public demo page where we could see the example application running.

I'm not a rails developer so I'm having a hard time installing all the code required to just be able to run the application. I had to go and research how to install bundler, then the install was breaking so I had to figure out why it was breaking, try to fix it or at least get it to run. Then I had to update my version of ruby, etc...

Thanks!

**Comment by sebicas** [comment]
There is a Demo App running at http://anatomyofbackbone.herokuapp.com

**Comment by jorgepedret** [comment]
Great! Thank you so much!

Gracias :-)
